version: '3.8'

services:
  git-scheduler:
    build: .
    container_name: git-deploy-scheduler
    volumes:
      # Mount repository to monitor
      - ${REPO_PATH:-./test-repo}:/repo
      # Mount config
      - ./config:/app/config
      # Mount logs
      - ./logs:/app/logs
      # Mount SSH keys for git authentication (optional)
      - ${HOME}/.ssh:/root/.ssh:ro
      # Mount git config (optional)
      - ${HOME}/.gitconfig:/root/.gitconfig:ro
    environment:
      # Override config via environment variables
      - REPO_PATH=/repo
      - OLLAMA_URL=${OLLAMA_URL:-http://oracle.local:11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.2:latest}
      - BASE_INTERVAL=${BASE_INTERVAL:-600}
      - JITTER_RANGE=${JITTER_RANGE:-50}
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME:-Auto Deploy Bot}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL:-bot@example.com}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    network_mode: host
    restart: unless-stopped
    # Run once mode: docker-compose run git-scheduler python main.py --once
    # Status mode: docker-compose run git-scheduler python main.py --status
