git:
  repo_path: /Users/justynroberts/work/git-deploy-schedule
  push_enabled: true
  retry_attempts: 3
  retry_delay: 5000

schedule:
  base_interval: 600
  jitter_range: 50
  enabled: true

ollama:
  enabled: true
  url: http://oracle.local:11434
  model: llama3.1:8b
  theme: kubernetes
  timeout: 30000

server:
  host: 0.0.0.0
  port: 3001
